 name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Environment File
        run: cp /home/slave/environment/cahaya-teknik/.env.ct-frontend.prod .env

      - name: Pull Latest Image
        run: docker pull 10.0.0.2:81/prod/ct-frontend:latest

      - name: Run Docker Compose
        run: docker compose  up -d
